# Generated by Django 4.2.4 on 2023-11-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='song',
            name='added_by',
        ),
    ]
