# Generated by Django 4.2.4 on 2023-11-30 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0002_remove_album_added_by_remove_artist_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_artists', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
    ]
