# Generated by Django 4.2.7 on 2023-11-26 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_album_artist_alter_album_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=datetime.datetime(2023, 11, 26, 4, 51, 17, 698022, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='base_app.album', verbose_name='Song Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='songThumbnail',
            field=models.ImageField(help_text='.jpg , .png , .jpeg , .gif , .svg supported', upload_to='thumbnail/', verbose_name='Song Thumbnail'),
        ),
    ]
